### ISSUE TITLE
手机端访问控制版面排版异常

### ISSUE THREAD

**Issue by LxDebug** [xggz/mqr#1]
![51F8B605-18A8-4837-B8AB-AECA1B111953](https://user-images.githubusercontent.com/27006147/101243633-8393d080-373c-11eb-8a56-820df7a08808.png)
在手机端访问时，排版异常，无法操作

**Comment by wisp-x** [comment]
页面暂未适配移动端

**Comment by xggz** [comment]
已简单适配移动端操作：
![image](https://user-images.githubusercontent.com/8168663/101327392-92e45c80-38a9-11eb-8cc1-8684a71fc2bc.png)
![image](https://user-images.githubusercontent.com/8168663/101327446-a68fc300-38a9-11eb-90d4-2b9ca7f5c2ac.png)
