### ISSUE TITLE
问一个傻傻的问题

### ISSUE THREAD

**Issue by fcm339** [xggz/mqr#14]
我去那个网站了，但是怎么获取聊天对话的ApiKey和ApiSecret。

**Comment by fcm339** [comment]
是不是只能设置这个Api，插件功能才能生效

**Comment by xggz** [comment]
获取ApiKey和ApiSecret很简单啊，登录控制台，然后添加一个机器人，机器人详情里面的api就有相关信息；

不设置这个Api，插件功能也会生效，只是闲聊插件不能使用

**Comment by fcm339** [comment]
谢谢大哥，我当时在控制台不知道是这样获取，其他插件的操作命令是啥

**Comment by xggz** [comment]
> 谢谢大哥，我当时在控制台不知道是这样获取，其他插件的操作命令是啥

https://github.com/xggz/mqr/issues/4#issuecomment-751197214
