### ISSUE TITLE
无法启动机器人

### ISSUE THREAD

**Issue by barbecue-pan** [xggz/mqr#3]
使用docker启动不了机器人
![image](https://user-images.githubusercontent.com/31641769/103074908-8419db80-4605-11eb-80f3-e3d08b91606d.png)

**Comment by xggz** [comment]
暂时无法登陆，请参考：

https://github.com/xggz/mqr/issues/2

**Comment by xggz** [comment]
已修复协议，Commit：https://github.com/xggz/mqr/commit/f18bc80d9502d1eb58ba6c754eb6d32b3abf33e5
