### ISSUE TITLE
怎么使用呢

### ISSUE THREAD

**Issue by barbecue-pan** [xggz/mqr#4]
用docker运行的
点击事件配置没有反应
左侧的5个tab也没效果

**Comment by xggz** [comment]
### 内置插件指令

**聊天插件（附带整点报时功能）：**
设置聊天前缀
设置报时类型
设置报时者名字

**抽签插件：**
观音灵签
月老灵签
财神爷灵签"

**笑话插件**
笑话
搞笑
段子

**群管插件：**
禁言
解禁
踢人
开启自动入群
关闭自动入群
开启入群欢迎
关闭入群欢迎
设置入群欢迎语"

**二维码插件：**
生成二维码
二维码生成

**签到插件：**
签到

**投票踢人插件：**
投票踢人
清空投票
清空投票次数
查询投票次数
查看投票次数
投票次数
清空全部投票
清空所有投票
设置踢人票数上限

**Comment by xggz** [comment]
> 用docker运行的
> 点击事件配置没有反应
> 左侧的5个tab也没效果

目前页面功能暂未全部开发，只支持页面登录控制，以及一些简单配置，截止当前时间，mqr内置的插件指令在上条消息已回复。

**Comment by sen-1210** [comment]
我想添加一些新的指令：添加好友

**Comment by fcm339** [comment]
抽签，笑话用不了啊，机器人是管理员，但是发不了图片是什么问题

**Comment by xggz** [comment]
> 抽签，笑话用不了啊，机器人是管理员，但是发不了图片是什么问题

不知道你为啥用不了，我的正常，可以去论坛或交流群反馈
